### ISSUE TITLE
Problem with non-acsii userprofile name on Windows (7)

### ISSUE THREAD

**Issue by danyaPostfactum** [TooTallNate/node-gyp#297]
Problem with `.vcxproj` file. node-gyp writes it in system codepage (non-utf8), while xml prolog specifies `utf-8` in `encoding` attribute. This causes error while trying to build the project.
My userprofile contains cyrillic characters, so I get non-ACSII characters in paths.

**Comment by knyazhe1** [comment]
@MattouFP
your "*Fix encoding problems in easy_xml.py*" (https://github.com/TooTallNate/node-gyp/pull/554):
```python
+ # Fix encoding
+ xml_string = unicode(xml_string, 'latin-1').encode(encoding)
```
is not working with cyrillic symbols :disappointed:
for correct work in this case  :ru: need another patch:
```python
+ # Fix encoding for cyrillc symbols
+ xml_string = unicode(xml_string, 'Windows-1251').encode(encoding)
```
This is not good solution in whole. Need a change solution provider maybe :interrobang:

**Comment by Sogl** [comment]
@knyazhe1, It not helps me...=(
Windows 8.1 x64, VS 2013 sp4

Can't install loopback:
http://loopback.io/getting-started/

Output:
```
C:\Users\Артем\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-s
upervisor\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\nod
ejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild )  else (rebuild)
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, до
бавьте параметр "/m".
C:\Users\Артем\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-
supervisor\node_modules\heapdump\build\addon.vcxproj(47,46): error MSB4025: не
удалось загрузить файл проекта. Недопустимый знак для указанной кодировки., стр
ока 47, позиция 46.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modul
es\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\
bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Артем\AppData\Roaming\npm\node_modules\strongloop\node_mod
ules\strong-supervisor\node_modules\heapdump
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
\
```

I.m from this issue https://github.com/TooTallNate/node-gyp/issues/404

**Comment by Sogl** [comment]
Finally fixed!
@MattouFP, @knyazhe1, thx for the solution!

My problem was in editing of the wrong file - easy_xml.py on Roaming folder (-g flag in install), but packet file runs node-gyp in Node.js installation directory.

**Comment by Chudesnov** [comment]
I believe this issue has to be re-opened.

Unfortunately, the fix provided in 39a06bc affects only Western (Latin-1) releases of Windows, as Cyrillic, Greek, Turkish, Hebrew, Arabic, Baltic and Vietnamese releases use different ANSI code pages.

There is, fortunately, a universal WinAPI method (available on Windows 2000 or higher) for detecting the default ANSI code page, `GetACP()`, used internally by the `locale` Python package. Using `locale.getdefaultlocale()[1]` instead of `"Latin-1"` fixes this issue on Cyrillic (Russian) Windows 8.1.

**Comment by polkovnikov-ph** [comment]
@Chudesnov Could you make it into a pull request, please? As it is obvious from the existence of this issue, Nathan doesn't have required skills to support this project. Even with such a deep detail on implementation it's quite unlikely this issue will get fixed.

**Comment by roman-yerin** [comment]
Still valid. Merge https://github.com/nodejs/node-gyp/pull/945 to fix it please
