### ISSUE TITLE
Python search should prefer "python2" executable

### ISSUE THREAD

**Issue by benesch** [TooTallNate/node-gyp#384]
On systems where Python 3 is the default, node-gyp complains about an incorrect Python version, even though Python 2 is often available as `python2`.

Per [PEP 394](http://www.python.org/dev/peps/pep-0394/):

> Python 2 only scripts should either be updated to be source compatible with Python 3 or else to use python2 in the shebang line

There are a few distributions that don't provide a `python2` executable. But searching PATH for both `python2` and `python` (and preferring `python2`) should catch cases where Python 2 is installed but node-gyp selects the wrong executable, while still supporting said distributions that don't ship a `python2`.

Is this something you guys'd endorse? If so, happy to provide a pull request.

**Comment by rgbkrk** [comment]
:+1:

**Comment by TooTallNate** [comment]
Fixed by #527.
