### ISSUE TITLE
`npm install -g node-gyp` fails

### ISSUE THREAD

**Issue by siddhion** [TooTallNate/node-gyp#418]
I've been having been trying to get MongoDB to start up properly with my Express.js app but when I run `node app.js` I get the `Failed to load c++ bson extension, using pure JS version` error. I should mention that when I ran `npm install` to install all the modules listed in `package.json` I got these two errors.
```
> kerberos@0.0.3 install /home/max/dev/3lf2/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> bson@0.2.5 install /home/max/dev/3lf2/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)
```
So I figured it was a problem with `node-gyp`. This is holding me back from moving forward with learning about Express and MongoDB. I'm not sure how to proceed so any help is super appreciated.

**Comment by TooTallNate** [comment]
Should be fixed by #527.
