### ISSUE TITLE
fatal error C1083: Cannot open include file: 'ammintrin.h'

### ISSUE THREAD

**Issue by CamiloMM** [TooTallNate/node-gyp#479]
Some people may have the same problem as me. I am trying to install a package that requires node-gyp on Windows 7 x64.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![It's like going to the dentist](https://cloud.githubusercontent.com/assets/2404138/3715194/cbafd7f0-15d4-11e4-893b-90ee796ae448.jpg)

I had Visual Studio 2013. I had to uninstall that, installed Python v2.7.3 and added it to the `PATH`, Microsoft Visual Studio C++ 2010, Uninstalled the C++ runtimes, installed Windows 7 64-bit SDK, the compiler update for the Windows SDK 7.1, and Microsoft Visual Studio C++ 2012 for Windows Desktop. Sometimes I found out the order was wrong, so I had to try a few times.

![Hope is all we have now](https://cloud.githubusercontent.com/assets/2404138/3715214/a002a3d4-15d5-11e4-94a8-5dd5b9b2f48e.jpg)

Thinking I would now be able to get started with Node.js on Windows, I tried installing [the package](http://nodeschool.io/#levelmeup) I had planned on installing. No good, I may need to get underwear that has "node-gyp" written on it. Or maybe my wallpaper is incompatible...

&nbsp;&nbsp;&nbsp;![We are powerless, broken and despaired](https://cloud.githubusercontent.com/assets/2404138/3715307/3575b416-15da-11e4-8ff0-6e85b038a7c9.jpg)

    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\intrin.h(26): fatal error C1083: Cannot open include file: 'ammintrin.h': No such file or directory

I then travelled to lands afar and consulted a fortune teller who has expertise with black magick and the arcane, and she told me it was the work of evil magi, and that I needed to consult the Red Mond scriptures and do a Ctrl+F for "how to dispel Demonic Witchcraft".

![Oh, Fortuna](https://cloud.githubusercontent.com/assets/2404138/3715336/f81a89d2-15db-11e4-9521-bc566f51f34c.jpg)

After consulting this sacred tome, I found out how to conjure the appropriate incantations that will fend off further satanic influences from Baphomet.

&nbsp;&nbsp;&nbsp;![He's actually a nice guy](https://cloud.githubusercontent.com/assets/2404138/3715351/e55bdf66-15dc-11e4-888e-614388d5df00.jpg)

It seems you need to install [Microsoft Visual Studio 2010 *Service Pack 1*](http://www.microsoft.com/downloads/en/confirmation.aspx?FamilyID=75568aa6-8107-475d-948a-ef22627e57a5) (at least I'm getting good at that), which may alleviate your boredom by presenting you with a shiny, brand-new error similar to this:

    ...\leveldown\node_modules\nan\nan.h(318): error C2039 : 'New' : is not a member of 'v8::String'

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![It's a "but plug"](https://cloud.githubusercontent.com/assets/2404138/3723894/8dcdd0a0-1678-11e4-94e0-1c51544f7cfe.jpg)

It seems this is because a module does not support the version of v8 bundled with Node. No biggie, one swipe of my magic wand and that pesky, uppity latest version of Node (0.11.x) is gone in favor of a more conservative, philistine version of Node from Mississippi (0.10.x).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![Stable version](https://cloud.githubusercontent.com/assets/2404138/3724362/7b9422e0-167d-11e4-9f0a-1c55806a8ecd.jpg)

So yeah, I just wanted to confirm that there *is* a candle at the end of the tunnel and that if some poor bastard needs to deploy Windows servers, one option would be running Windows VMs that have been carefully set up to support node-gyp.

So two clarifications could be added:

* You may need [Microsoft Visual Studio 2010 *Service Pack 1*](http://www.microsoft.com/downloads/en/confirmation.aspx?FamilyID=75568aa6-8107-475d-948a-ef22627e57a5)
* There has been some changes to v8 recently so if things go haywire, check if they work on older Node (I realise this is not node-gyp or gyp's fault).

![Freedom at last!](https://cloud.githubusercontent.com/assets/2404138/3725268/04669568-1687-11e4-9fd5-2f27287416c4.jpg)

**Comment by JK1337** [comment]
Fortunately you can just copy a working file and include it into the folder "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\"

**Comment by TerribleDev** [comment]
That is why this exists https://www.npmjs.com/package/windows-build-tools

**Comment by webstuffer** [comment]
Try with "npm install --global windows-build-tools" and then run "npm install".
It worked for me.

**Comment by akontsevich** [comment]
@TerribleDev @webstuffer windows-build-tools does not help on Azure.

**Comment by TerribleDev** [comment]
@akontsevich azure is a giant amalgamation of products and services. I know for a fact it works on windows based scaling sets. Of course it does not work on linux VM's or containers. What do you mean by 'doesnt work on azure', do you mean app services, functions, etc?

**Comment by akontsevich** [comment]
@TerribleDev app services and Kudu.

**Comment by TerribleDev** [comment]
@akontsevich You can compile your native modules outside kudu, using something like appveyor, VSTS, and then upload them. 

I believe you are running into the limitations of the [azure app sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox)

**Comment by akontsevich** [comment]
> You can compile your native modules outside kudu, using something like appveyor, VSTS, and then upload them.

I did that. Thanks.

**Comment by CamiloMM** [comment]
@werewolfdev People still suffer from `node-gyp`? Wow! Does it still require hand-cranked Python 2.7?

Sorry for the unhelpful response, but I'm kinda amazed if you didn't arrive here by mistake, somehow!

**Comment by cclauss** [comment]
> Does it still require hand-cranked Python 2.7?

Of course not.  Python 2 died 711 days ago on 1/1/2020 so it is no longer supported.  This codebase uses Python f-strings so any Python < 3.6 is not supported.  https://github.com/nodejs/node-gyp#installation
