### ISSUE TITLE
Use the right python binary

### ISSUE THREAD

**Issue by Yamakaky** [TooTallNate/node-gyp#524]
Hi

It looks like that you use only python2. It's perfectly fine, but you also seems to use /usr/bin/python. In archlinux, it's a symlink to python3. You should use /usr/bin/python2 instead.

**Comment by mikemorris** [comment]
From the README:
> If you have multiple Python versions installed, you can identify which Python version node-gyp uses by setting the '--python' variable:

> $ node-gyp --python /path/to/python2.7

> If node-gyp is called by way of npm and you have multiple versions of Python installed, then you can set npm's 'python' config key to the appropriate value:

> $ npm config set python /path/to/executable/python2.7

**Comment by Yamakaky** [comment]
Well, `npm config` works, but if gyp only supports python2, you should modify the shebang for it to work out of the box.

**Comment by TooTallNate** [comment]
Fixed by #527.
