### ISSUE TITLE
Gyp should check for python2 executable if default python is 3

### ISSUE THREAD

**Issue by bendavis78** [TooTallNate/node-gyp#526]
It's fairly standard these days (at least in *nix flavors) to have "python2" and "python3" binaries installed in an environment where both versions are used. Ideally gyp should check for a python2 executable in the path.  

Gyp currently allows explicitly setting --python, however  one should only need to use this in special cases, not every time npm is called. You can also set the PYTHON environment variable in your .bashrc, but this variable is fairly generic and might affect other programs that depend on it to mean "the default python on this system".

**Comment by TooTallNate** [comment]
Fixed by #527.
