### ISSUE TITLE
MSVS: ability to set GenerateDebugInformation to false

### ISSUE THREAD

**Issue by j0tunn** [TooTallNate/node-gyp#551]
Current realization just forces `GenerateDebugInformation` project setting to true. Could you, please, make it configurable, for example when `--no-debug` option is set.
In my environment (vagrant, windows, ssh, VS 2013 Express) I'm getting error `LINK : fatal error LNK1101: incorrect MSPDB120.DLL version` during build when linker tries to generate pdb file. I don't need that file at all, but I just can't disable this setting. 

As a workaround I've tried to hardcode it to false [here](https://github.com/TooTallNate/node-gyp/blob/d62787edf8b48fdf9b9813f535c62cf27783c76b/gyp/pylib/gyp/MSVSUtil.py#L254), but no luck.

**Comment by deepak1556** [comment]
You can override in `VCLinkerTool` settings
```
          'VCLinkerTool': {
            'GenerateDebugInformation': 'false',
```

**Comment by j0tunn** [comment]
@deepak1556 that works, htanks.
