### ISSUE TITLE
Is there a way to make it work with Visual Studio 2015

### ISSUE THREAD

**Issue by koistya** [TooTallNate/node-gyp#555]
```
remote:   File "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\node_modules\node-gyp\g
yp\pylib\gyp\MSVSVersion.py", line 402, in SelectVisualStudioVersion
remote:     versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
remote: KeyError: '14.0'
remote: gypnpm ERR! contextify@0.1.11 install: `node-gyp rebuild`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the contextify@0.1.11 install script.
remote: npm ERR! This is most likely a problem with the contextify package,
remote: npm ERR! not with npm itself.
remote: npm ERR! Tell the author that this fails on your system:
remote: npm ERR!     node-gyp rebuild
remote: npm ERR! You can get their info via:
remote: npm ERR!     npm owner ls contextify
remote: npm ERR! There is likely additional logging output above.
remote:
remote: npm ERR! System Windows_NT 6.2.9200
remote: npm ERR! command "D:\\Program Files (x86)\\nodejs\\0.10.32\\node.exe" "D:\\Program
 Files (x86)\\npm\\1.4.28\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs-version=14.0"
remote: npm ERR! cwd D:\home\site\wwwroot
remote: npm ERR! node -v v0.10.32
remote: npm ERR! npm -v 1.4.28
remote: npm ERR! code ELIFECYCLE
```

**Comment by springmeyer** [comment]
To get this working we'll need to upgrade gyp to include https://code.google.com/p/gyp/source/detail?r=2013

**Comment by Globegitter** [comment]
Yep just tried with VS2015 as well - would love to see support for it.

**Comment by build-your-web** [comment]
+1

**Comment by domderen** [comment]
+1

**Comment by tonidy** [comment]
+1

**Comment by vicentedealencar** [comment]
+1

**Comment by toddpi314** [comment]
+1 - this is blocking a few teams working on building NPM backed WUP apps for Win10

**Comment by voku** [comment]
+1

**Comment by Dmitra** [comment]
+1

**Comment by toddpi314** [comment]
So, it says pretty clearly in the docs that you have to have VS C++ 2012/2013 installed.
https://github.com/TooTallNate/node-gyp#installation

After doing this, I was able to build in VS2015 just fine.

**Comment by Dmitra** [comment]
I experience this issue having only VS2012/13 installed
The issue appeared after removing VS2010. That was done intentionally, because older VS versions doesn't support some modern features to build https://www.npmjs.com/package/sharp

![libcpmt lib missing](https://cloud.githubusercontent.com/assets/280060/7743153/8b07a55a-ffa0-11e4-9785-6aefe6915b61.jpg)

**Comment by TooTallNate** [comment]
Please try node-gyp v2.0.0, which updated gyp to include MSVS 2015 support.

**Comment by Dmitra** [comment]
not sure about VS2015 installed alone, but for VS2012/13 on Windows8.1 the issue remains.
As soon as nodejs installation doesn't include node-gyp 2.0.0 yet, I replaced old version with 2.0 manually. But the issue is still there.
![node-gyp2](https://cloud.githubusercontent.com/assets/280060/7877584/ccd3e156-05e5-11e5-891e-2783cbe3ce79.jpg)

**Comment by Dmitra** [comment]
thank you very much, the issue is gone with VS2015 installation

**Comment by jasonwilliams200OK** [comment]
:+1:
libuv is also updated to build with VS2015 in v1.6.0+
https://github.com/libuv/libuv/releases/tag/v1.6.0

**Comment by GregS2** [comment]
I'm trying to install the iron-meteor/iron-cli package, and I'm getting the same error as Dmitra. I think the problem might be that it's trying to use an old version of node-gyp, despite the fact that I do have V2 installed.(verified with npm list -g node-gyp). Referring to the highlighted node-gyp version in Dmitra's screen grab - it says V1.0.3 for me in my log.  Any ideas why it's trying to use an older version of node-gyp?

**Comment by GregS2** [comment]
Fixed! I think the root cause was that I had not updated npm using the proper process for Windows. (along with node-gyp having not been updated initially)

**Comment by Mirodil** [comment]
+1

**Comment by moogus** [comment]
http://www.serverpals.com/blog/building-using-node-gyp-with-visual-studio-express-2015-on-windows-10-pro-x64

**Comment by karimcitoh** [comment]
+1

**Comment by godlzr** [comment]
+1

**Comment by ioanb7** [comment]
+1, using vs 2015
