### ISSUE TITLE
support io.js?

### ISSUE THREAD

**Issue by fengmk2** [TooTallNate/node-gyp#561]
Any plan to support build c++ module for io.js?

**Comment by springmeyer** [comment]
I've found that node-gyp supports io.js without modifications. If you are seeing build problems it is likely that the C++ Addon you are using needs to update its use of the V8 API. If the C++ addon you are trying to install uses Nan (https://github.com/rvagg/nan) then you'll need to be patient until a new Nan release comes out with these fixes https://github.com/rvagg/nan/issues/225.

**Comment by TooTallNate** [comment]
What @springmeyer said :smile:

**Comment by fengmk2** [comment]
Thanks :)

**Comment by ilkkao** [comment]
New nan release with iojs support is now available.

**Comment by fengmk2** [comment]
https://github.com/TooTallNate/node-gyp/pull/564
