### ISSUE TITLE
Python 2.7.3 (64-bit) for Windows 7 (64-bit)?

### ISSUE THREAD

**Issue by hezjing** [TooTallNate/node-gyp#578]
Hi

I'm trying to install the prerequisite described in [the installation steps](https://github.com/TooTallNate/node-gyp). It is not clear to me which Python 2.7.3 installer to download if I'm using Windows (64-bit) and Node.js v0.12.0 (64-bit):

* Windows x86 MSI Installer or,
* Windows X86-64 MSI Installer?

Well, my best guess is the Windows x86-64 MSI but I just want to be sure.

**Comment by TooTallNate** [comment]
It probably shouldn't matter. But you should try to match the version of your operating system, so 64-bit in this case.
