### ISSUE TITLE
What commit is tagged 1.0.2?

### ISSUE THREAD

**Issue by kevinsawicki** [TooTallNate/node-gyp#579]
1.0.2 is showing here: https://www.npmjs.com/package/node-gyp

But there doesn't seem to be a 1.0.2 tag here: https://github.com/TooTallNate/node-gyp/tree/v1.0.2

**Comment by TooTallNate** [comment]
https://github.com/TooTallNate/node-gyp/commit/1e399b471945b35f3bfbca4a10fba31a6739b5db. I'll add a tag. Thanks for the poke.

**Comment by TooTallNate** [comment]
Tagged!
