### ISSUE TITLE
Problem with Distros that use Python 3 as default /usr/bin/python

### ISSUE THREAD

**Issue by jnbek** [TooTallNate/node-gyp#581]
On Arch Linux ( maybe others? ) the default python version is the 3.x series. /usr/bin/python calls this series and scripts requiring python 2.5+ must be prefixed as /usr/bin/python2.

This is fine for command line usage of the node-gyp utility, however in many PKGBUILDs for nodejs packages that use node-gyp as the build system, this occasionally happens transparently, in the PKGBUILDs the module's files are acquired running:

npm install $args $pkgname

and this means that npm goes and tries to be all helpful and download/install any dependencies that are needed. In this case, calipso is an example of this, it attempts to install the bcrypt module which in turn uses node-gyp.

Right about now, you're asking "What does this have to do with me? I added the --python flag to address this!" I'm glad you asked this ;-) in PKGBUILDs we can set environment variables much easier than perhaps using sed to grok the gyp calls in the bcrypt module to add the --python flag, this would be very hacky and messy. My request at this point is to allow for the --python flag to be set using an environment variable:

USE_PYTHON=/usr/bin/python2 npm install -g --prefix "$pkgdir/usr" $_npmname@$_npmver

so, if that ( or whatever named environment variable you choose ) is set, nodejs-gyp will set the --python flag based off the contents of that variable.

Another possible solution perhaps would be to try/catch python --version and if it's 3.X check for $PATH/python2 and use that as it's default python. Other distros are beginning to make the move to python3 for default version, Fedora is discussing this for sure and I'm sure others are as well, so it may be prudent to do some backend version sniffing and attempt to find the python2 binary and if not able, then error out mentioning use of the --python flag or the environment variable.

**Comment by apaatsio** [comment]
This should work `PYTHON=/usr/bin/python2 npm install [...]`

**Comment by jnbek** [comment]
hmm, ok, I'll give it a try momentarily

**Comment by TooTallNate** [comment]
Fixed by #527.
