### ISSUE TITLE
node-gyp reinstalls node for some reason ?

### ISSUE THREAD

**Issue by redben** [TooTallNate/node-gyp#591]
I found this gist by @mcqueenorama https://gist.github.com/mcqueenorama/174f5f325fb35251578e (I have the same problem) 
But could not find any discussion linking to it.

Why does node-gyp redownload node ?

node v0.12.0
npm 2.5.1
node-gyp v1.0.3
OS X Yosemite
(node installed via nvm FWIW)

What do these lines mean ?
> gyp verb install version is already installed, need to check "installVersion"
> gyp verb got "installVersion" 0
> gyp verb needs "installVersion" 9
> gyp verb install version is no good; reinstalling

**Comment by mcqueenorama** [comment]
There's a version file in there and it needs to have the version of something.  In this case of an ugly hack,  it was on a server with no network connectivity so it could not get the source code. I don't know why it wants 9.  It looks like the versions are all correct, so I put the right node source code in there and jammed a 9 in that file, and it started working.  Maybe somebody will explain the "why".

l-sclX1Q0DV7-M:lib bmcquee$ ls -a ~/.node-gyp/0.10.32/
.		..		common.gypi	deps		installVersion	src		tools
l-sclX1Q0DV7-M:lib bmcquee$ cat !$
cat ~/.node-gyp/0.10.32/installVersion
9

**Comment by CooCooooo** [comment]
@redben @mcqueenorama 
install ---------- Installs node development header files for the given version

run  " node-gyp install "  first may solve you problem

**Comment by redben** [comment]
Thanks @mcqueenorama  @CooCooooo
