### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by andhikanugraha** [TooTallNate/node-gyp#632]
Hi,

In Microsoft's Node fork, MSVSVersion.py was modified slightly to support VS2015: Microsoft/node@ed002595f1a699f8e6951df260f34fe70ab81a09

Can we port this to the main repo? With Windows 10 and Visual Studio 2015 just around the corner I think Windows users will be quite happy :)

**Comment by TooTallNate** [comment]
Please try node-gyp v2.0.0, which updated gyp to include MSVS 2015 support.
