### ISSUE TITLE
Unable to use node-gyp on the intranet

### ISSUE THREAD

**Issue by msmolyak** [TooTallNate/node-gyp#665]
I am trying to install/build node modules onthe intranet. I have access to the internal NPM repository mirroring npmjs.org, but no connection to the internet.

When I run npm install (or 'node-gyp configure build' directly), the program attempts to download https://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz, which it clearly cannot without the access to the internet. I do have this file available on my intranet.

How do I instruct node-gyp to use the local version of this file? How do I use the tool offline?

**Comment by TooTallNate** [comment]
You can untar the tarball into a directory, and then point node-gyp to that directory with the `--nodedir` flag. Cheers!

**Comment by nickboldt** [comment]
or don't unpack the tarball and use it as is. 

```
NODE_VER=v10.14.1
curl -sSL https://nodejs.org/download/release/${NODE_VER}/node-${NODE_VER}-headers.tar.gz \
        -o /tmp/node-headers.tgz; \
npm config set tarball /tmp/node-headers.tgz
```
