### ISSUE TITLE
iojs issue installing node-gyp

### ISSUE THREAD

**Issue by sarasfox** [TooTallNate/node-gyp#670]
I was installing jquerygo and fail traced it back to node-gyp not setting up weak for Phantom.js

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.4.0/node-v2.4.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "/usr/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gadget-girl/tiretask/App/testing/node_modules/weak
gyp ERR! node -v v2.4.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/iojs" "/usr/local/bin/npm" "install" "weak"
npm ERR! node v2.4.0
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE

npm ERR! weak@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weak@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gadget-girl/tiretask/App/testing/npm-debug.log

**Comment by klimashkin** [comment]
Same issue, when using iojs, every package, which want to be built, node-gyp try to download iojs dist from http://nodejs.org/dist/v

**Comment by TooTallNate** [comment]
At this time, you _must_ use the copy of npm that ships with io.js, otherwise it attempts to download the tarball from nodejs.org rather than iojs.org.
