### ISSUE TITLE
Linker error when rebuilding addon

### ISSUE THREAD

**Issue by gerhardberger** [TooTallNate/node-gyp#675]
hi

I made an example that used the Hello World example and it worked fine, but after some time it started throwing a linker error when I wanted to rebuild the addon. I can't say it surely but I think it started to throw the error after I updated to El Capitan beta 4 from beta 3.
after I rebuild with:
``` bash
node-gyp rebuild
```
I get this error:
``` bash
...
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/binding/addon.o
  SOLINK_MODULE(target) Release/binding.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/binding.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/gerhard/Desktop/examples/gyptest
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```
I checked and I have a `libgcc_s.10.5.tbd` file in my `/usr/lib` folder and I reinstalled `node-gyp` too.

thanks

**Comment by gerhardberger** [comment]
The issue might be on the OS side, because in El Capitan there is a `.tbd` extension for dynamic libraries and that might cause the problem. I haven't been able to solve it yet though.

**Comment by gerhardberger** [comment]
The problem was that I didn't used the *Command Line Tools* of Xcode **7**.
With that it's working fine!

**Comment by gerhardberger** [comment]
The problem was that I didn't used the *Command Line Tools* of Xcode **7**.
With that it's working fine!

**Comment by YComputer** [comment]
I changed to use iTerm but still doesn't work.

**Comment by jferiante** [comment]
I have the same issue.

**Comment by MartijnR** [comment]
seems relevant: https://github.com/Homebrew/homebrew/issues/40653
