### ISSUE TITLE
non-option action command line arguments are prefixed with the relative path to the gyp file

### ISSUE THREAD

**Issue by Mossop** [TooTallNate/node-gyp#677]
I use some custom actions to download and extract source files that my project depends on. They work fine on OSX and Linux but on Windows the commands that eventually get called have their arguments altered. It looks like specifically if arguments start with "-" or a variable of some kind then they pass through fine, otherwise they are prefixes with the relative path from the build directory to the gyp file's directory.

For example:

    "action": [ "curl", "-L", "-o", "<(INTERMEDIATE_DIR)/flam3.tar.gz", "<(flam3_archive)" ]

in the gyp file becomes:

    <Command>call call curl &quot;-L&quot; &quot;-o&quot; &quot;$(IntDir)flam3.tar.gz&quot; &quot;..\..\deps\https:\github.com\scottdraves\flam3\archive\v3.1.1.tar.gz&quot;&#xD;&#xA;if %errorlevel% neq 0 exit /b %errorlevel%</Command>

in the vcxproj file for that action, "..\..\deps\" is the prefix that got added to that variable's value.

Likewise there is this example:

    "action": [ "tar", "-xmv", "--strip-components", "1", "-C", "<(flam3_dir)", "-f", "<(INTERMEDIATE_DIR)/flam3.tar.gz" ]

becomes:

    <Command>call call tar &quot;-xmv&quot; &quot;--strip-components&quot; &quot;..\..\deps\1&quot; &quot;-C&quot; &quot;$(OutDir)obj\global_intermediate\flam3&quot; &quot;-f&quot; &quot;$(IntDir)flam3.tar.gz&quot;&#xD;&#xA;if %errorlevel% neq 0 exit /b %errorlevel%</Command>

**Comment by TooTallNate** [comment]
This is part of gyp itself, node-gyp doesn't really have any control here. It sounds like you've already figured out the workaround though: put the commands into a variable first.

**Comment by Mossop** [comment]
Do you have any details on the gyp issue? Putting a variable at the start only works if it contains a path which doesn't help for most cases.
