### ISSUE TITLE
Transfer to the nodejs org?

### ISSUE THREAD

**Issue by Fishrock123** [TooTallNate/node-gyp#688]
@TooTallNate how do you feel about this proposal? We can create a separate team for it and whatnot, do you have any concerns about it?

Given it is very much tied to the node.js/io.js build and distribution systems I think it could be better managed among a group there, probably with connection to the build team. The close ties to to the build/dist systems can be seen in some of the more recent floating patches in https://github.com/nodejs/node/commits/master/deps/npm/node_modules/node-gyp, making nightlies and whatnot work on it.

cc @rvagg / ?

**Comment by TooTallNate** [comment]
I'm :+1:. This is pretty much a dup of #627.
